name: collab_sim
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.13
  - pip=23.3.1
  - python=3.10.13
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2024a
  - wheel=0.41.2
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - chardet==5.2.0
      - cloudpickle==3.0.0
      - cmake==3.28.3
      - colorlog==6.8.2
      - contourpy==1.2.1
      - embreex==2.17.7.post4
      - fonttools==4.51.0
      - gym==0.26.2
      - gym-notices==0.0.8
      - httpcore==1.0.4
      - httpx==0.27.0
      - imageio==2.34.0
      - importlib-resources==6.1.2
      - lazy-loader==0.4
      - lit==17.0.6
      - mapbox-earcut==1.0.1
      - ninja==1.11.1.1
      - numpy==1.26.3
      - pybind11==2.12.0
      - pycollada==0.8
      - pyqt5==5.15.10
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.13.0
      - pyqtgraph==0.13.7
      - rtree==1.2.0
      - scikit-image==0.22.0
      - shapely==2.0.3
      - svg-path==6.3
      - tifffile==2024.2.12
      - torchtyping==0.1.4
      - tqdm==4.66.2
      - transforms3d==0.4.1
      - trimesh==4.1.7
      - triton==2.0.0
      - typeguard==4.1.5
      - typing-extensions==4.10.0
      - vhacdx==0.0.5
      - warp-lang==0.13.0
      - xatlas==0.0.9
      - xxhash==3.4.1
      - yourdfpy==0.0.56
